brand new verson that uses ftp, turns out to be faster than rsync
Still needs some work

git-svn-id: file:///srv/svn/joey/bintrunk@926 a4a2c43b-8ac3-0310-8836-e0e880c912e2

diff --git a/debmirror b/debmirror
--- a/debmirror
+++ b/debmirror
@@ -1,125 +1,202 @@
-#!/bin/sh -e
-# Anon rsync partial mirror of Debian with package pool support.
-# Copyright 1999, 2000 by Joey Hess <joeyh@debian.org>, GPL'd.
+#!/usr/bin/perl
 #
-# This script generates a partial mirror, including only one architecture,
-# optional source, and a few other things. It supports package pools, and
-# operates via rsync.
-# 
-# Once you have the mirror, an apt line similar to the following will
-# allow it to be used:
-#
-# deb file:/mirror/debian unstable main non-free contrib non-US/main non-US/contrib non-US/non-free
-# deb-src file:/mirror/debian unstable main non-free contrib non-US/main non-US/contrib non-US/non-free
+# Debian partial mirror script, with ftp and package pool support.
+# Copyright 2001 Joey Hess <joeyh@debian.org>, GPL'd.
 
-# Flags to pass to rsync. More can be specified on the command line.
-# These flags are always passed to rsync:
-FLAGS="$@ -rLpt --partial"
-# These flags are not passed in when we are getting files from pools.
-# In particular, --delete is a horrid idea at that point, but good here.
-FLAGS_NOPOOL="$FLAGS --exclude Packages --delete"
-# And these flags are passed in only when we are getting files from pools.
-# Remember, do _not_ include --delete.
-FLAGS_POOL="$FLAGS"
-# The host to rsync from. Include the rsync module name/directory
-# for debian.
-HOST=zeus.kernel.org::mirrors/debian
-# The host to rsync non-us from. Include the rsync module name/directory
-# for debian/non-US
-HOST_NONUS=pandora.debian.org::debian-non-US
-# Where to put the mirror (absolute path, please):
-DEST=/mirror/debian
-# The distribution to mirror:
-DIST=unstable
-# Architecture to mirror:
-ARCH=i386
-# Should source be mirrored too?
-SOURCE=yes
-# How about the debian-installer? (All of it, this is a little imperfect..)
-DEBIAN_INSTALLER=yes
-# The sections to mirror (main, non-free, etc):
-SECTIONS="main contrib non-free"
-# Should a contents file kept up to date?
-CONTENTS=yes
-# Should symlinks be generated to every deb, in an "all" directory?
-# I find this is very handy to ease looking up deb filenames.
-SYMLINK_FARM=yes
+# TODO: remove all empty directories.
+# TODO: my symlink farm thing.
+# TODO: non-us!
 
-###############################################################################
+#######################################################################################
+# Configure this program here:
 
-mkdir -p $DEST/dists $DEST/pool
+# The system to mirror from.
+my $hostname="ftp.kernel.org";
+# Root of the remote debian mirror.
+my $remoteroot="/debian";
+# WHere to put the local mirror.
+my $localroot="/mirror/debian";
+# List of distributions to mirror.
+my @dists=qw{unstable};
+# List of sections to mirror.
+my @sections=qw{main contrib non-free};
+# List of architectures to mirror (include binary- prefix)
+my @arches=qw{binary-i386 debian-installer/binary-i386};
+# List of sources to mirror (generally either ('source') or empty.
+my @sources=qw{source};
+# Should I do slow, paranoid md5 checks to catch files that are of same size as
+# what is listed in Packages/Sources files, but do not md5sum the same.
+my $check_md5sums=0;
 
-# Snarf the contents file.
-if [ "$CONTENTS" = yes ]; then
-	mkdir -p $DEST/misc
-	rsync $FLAGS_NOPOOL \
-		$HOST/dists/$DIST/Contents-${ARCH}.gz \
-		$DEST/misc/ || true
-fi
+#######################################################################################
 
-if [ "$SOURCE" = yes ]; then
-	SOURCE=source
-else
-	SOURCE=""
-fi
+use warnings;
+use strict;
+use Net::FTP;
+use Getopt::Long;
 
-if [ "$DEBIAN_INSTALLER" = yes ]; then
-	DEBIAN_INSTALLER=debian-installer
-else
-	DEBIAN_INSTALLER=""
-fi
+# Parse command line.
+my ($debug, $progress);
+GetOptions(
+	'debug|d' => \$debug,
+	'progress|p' => \$progress,
+) or die "Syntax: $0 [-d|-p]\n";
 
-# Download packages files.
-for type in binary-${ARCH} $DEBIAN_INSTALLER $SOURCE; do
-	for section in $SECTIONS; do
-		mkdir -p $DEST/non-US/$section/$type $DEST/$section/$type
-		rsync $FLAGS_NOPOOL \
-			$HOST_NONUS/dists/$DIST/non-US/$section/$type \
-			$DEST/non-US/$section/ || true
-		rsync $FLAGS_NOPOOL \
-			$HOST/dists/$DIST/$section/$type \
-			$DEST/$section/ || true
-	done
-done
+# Set up mirror directory.
+make_dir($localroot);
+chdir($localroot) or die "chdir $localroot: $!";
 
-# Update the package pool.
-# TODO: probably needs to be optimized, we'll see as time goes by..
-cd $DEST || exit 1 # If this fails, we're screwed.
-rm -f .filelist
+# Start up ftp.
+my $ftp;
+if ($progress) {
+	$ftp=Net::FTP->new($hostname, Debug => $debug, Hash => *STDOUT);
+}
+else {
+	$ftp=Net::FTP->new($hostname, Debug => $debug);
+}
+$ftp->login; # anonymous
+$ftp->binary;
 
-# Get a list of all the files that are in the pool based on the Packages
-# files that were already updated. Thanks to aj for the awk-fu.
-find $DEST -name Packages.gz | \
-	xargs -r zgrep -i ^Filename: | cut -d ' ' -f 2 > .filelist
-find $DEST -name Sources.gz | xargs -r zcat | \
-	awk '/^Directory:/ {D=$2} /Files:/,/^$/ { \
-		if ($1 != "Files:" && $0 != "") print D "/" $3; \
-	     }' >> .filelist
+# This hash holds all the files we know about, If the hash key is false,
+# the file already exists in the mirror and does not need to be downloaded,
+# if it is true the file needs to be downloaded. Filenames should be
+# relative to $localroot.
+my %files;
 
-# Make all dirs. I think perl is the fastest way.
-perl -ne 's![^/]*$!!; $dirs{$_}=1; END { system "mkdir -p ".join(" ", keys %dirs) }' .filelist
+# Get Packages and Sources files and other miscellany.
+my (@package_files, @source_files);
+foreach my $dist (@dists) {
+	foreach my $section (@sections) {
+		foreach my $arch (@arches) {
+			my $subdir="dists/$dist/$section/$arch";
+			$ftp->cwd("$remoteroot/$subdir") or
+				warn "skipping $remoteroot/$subdir\n" and next;
+			make_dir($subdir);
+			ftp_get("Packages.gz", "$subdir/Packages.gz") and
+				push @package_files, "$subdir/Packages.gz";
+			$files{"$subdir/Packages.gz"}=0;
+			# Get the release file later.
+			$files{"$subdir/Release"}=1;
+		}
+		foreach my $source (@sources) {
+			my $subdir="dists/$dist/$section/$source";
+			$ftp->cwd("$remoteroot/$subdir") or
+				warn "skipping $remoteroot/$subdir\n" and next;
+			make_dir($subdir);
+			ftp_get("Sources.gz", "$subdir/Sources.gz") and
+				push @source_files, "$subdir/Sources.gz";
+			$files{"$subdir/Sources.gz"}=0;
+		}
+	}
+}
 
-# Tell rsync to download only the files in the list. The exclude is here 
-# to make the recursion not get anything else. The two pools from the
-# mirror are actually merged into one local pool; rsync handles that just
-# fine.
-rsync $FLAGS_POOL $HOST_NONUS --include-from .filelist --exclude '*' .
-rsync $FLAGS_POOL $HOST --include-from .filelist --exclude '*' .
-# Delete all files that are not in the list, then any empty directories.
-# This also kills the filelist. Have to exclude the stuff we download
-# that's not in the filelist though.
-find -type f | sed s:\./:: | fgrep -vxf .filelist | grep -v Packages | \
-	grep -v Sources | grep -v Contents | xargs -r rm -f
-find -type d -empty | xargs -r rmdir -p --ignore-fail-on-non-empty
-# End of package pool update.
+# Parse Packages and Sources files and add to the file list everything therein.
+$/="\n\n";
+my ($filename, $size, $md5sum, $md5, $directory);
+if ($check_md5sums) {
+        eval q{use Digest::MD5};
+	$md5=Digest::MD5->new;
+}
+foreach my $file (@package_files) {
+	open IN, "zcat $file|" or die "$file: $!";
+	while (<IN>) {
+		($filename)=m/^Filename:\s+(.*)/im;
+		($size)=m/^Size:\s+(\d+)/im;
+		($md5sum)=m/^MD5sum:\s+([A-Za-z0-9]+)/im;
+		$files{$filename}=check_file($filename, $size, $md5sum);
+	}
+	close IN;
+}
+foreach my $file (@source_files) {
+	open IN, "zcat $file|" or die "$file: $!";
+	while (<IN>) {
+		($directory) = m/^Directory:\s+(.*)/im;
+		while (m/^ ([A-Za-z0-9]{32} .*)/mg) {
+			($md5sum, $size, $filename)=split(' ', $1, 3);
+			$filename="$directory/$filename";
+			$files{$filename}=check_file($filename, $size, $md5sum);
+		}
+	}
+	close IN;
+}
 
-# Update symlinks (I like to have a link to every .deb in one directory).
-if [ "$SYMLINK_FARM" = yes ]; then
-	install -d  $DEST/all
-	cd $DEST/all || exit 1
-	find -name \*.deb -or -name \*.udeb | xargs -r rm -f
-	find .. -name "*.deb" -or -name \*.udeb -type f | \
-		grep -v ^../all | xargs -r -i ln -sf {} .
-fi
+# Download all files that we need to get.
+$ftp->cwd($remoteroot) or die "cdw to $remoteroot failed";
+my $dirname;
+foreach my $file (sort keys %files) {
+	if ($files{$file}) {
+		($dirname) = $file =~ m:(.*)/:;
+		make_dir($dirname);
+		ftp_get($file, $file);
+	}
+	else {
+		print "skipping $file\n" if $debug;
+	}
+}
 
-# Waste bandwidth. Put a partial mirror on your laptop today!
+$ftp->quit;
+
+# Now clean up the mirror. First, remove all files in the mirror that
+# we don't know about.
+$/="\n";
+foreach my $file (`find . -type f`) {
+	chomp $file;
+	$file=~s:^\./::;
+	unless (exists $files{$file}) {
+		print "deleting $file\n" if $debug;
+		unlink $file or die "unlink $file: $!";
+	}
+}
+# Then remove all empty directories.
+system("find . -type d -empty | xargs -r rmdir -p --ignore-fail-on-non-empty");
+
+# Pass this function a filename, a file size (bytes), and a md5sum (hex).
+# It will return true if the file nees to be downloaded.
+sub check_file {
+	my ($filename, $size, $md5sum)=@_;
+	if (-f $filename and $size == -s _) {
+		if ($check_md5sums) {
+			open HANDLE, $filename or
+				die "$filename: $!";
+			$md5->addfile(*HANDLE);
+			if ($md5sum eq $md5->hexdigest) {
+				return 0;
+			}
+		}
+		else {
+			# Assume it is ok, w/o md5 check.
+			return 0;
+		}
+	}
+
+	return 1;
+}
+
+# Get a file via ftp, first displaying its filename if progress is on.
+# I should just be able to subclass Net::Ftp and override the get method,
+# but it's late.
+sub ftp_get {
+	print "$_[0]: " if $progress;
+	my $ret=$ftp->get(@_);
+	print "failed\n" if ! $ret;
+	return $ret;
+}
+
+# Make a directory including all needed parents.
+{
+	my %seen;
+	
+	sub make_dir {
+		my $dir=shift;
+		
+		my @parts=split('/', $dir);
+		my $current='';
+		foreach my $part (@parts) {
+			$current.="$part/";
+			if (! $seen{$current}) {
+				mkdir $current;
+				$seen{$current}=1;
+			}
+		}
+	}
+}
